/******************************************************************************
*
* Module: Ultrasonic
*
* File Name: ultrasonic.h
*
* Description: Header file for the Ultrasonic driver
*
* Author: Abdallah El-Sakka
*
*******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "../../Utils/std_types.h"

/*******************************************************************************
*                                Definitions                                  *
*******************************************************************************/

#define ECHO_PORT_ID	(PORTD_ID)
#define ECHO_PIN_ID		(PIN6_ID)

#define TR_PORT_ID		(PORTD_ID)
#define TR_PIN_ID		(PIN7_ID)

#define TR_DELAY        (10u)

#define F_PRESCALER     (8u)

#define SPEED_OF_SOUND  (34000UL)

/*******************************************************************************
 *                      Functions Prototypes                                   *
*******************************************************************************/

/*
 * Initialize the ICU driver as required.
 * Set up the ICU callback function.
 * Set the direction for the trigger pin as output through
 * the GPIO driver
 */
void Ultrasonic_init(void);

/*
 * Send the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Send the trigger pulse by using the Ultrasonic_Trigger
 * function.
 * Start the measurement process via the ICU driver.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * This is the callback function called by the ICU driver.
 * It calculates the high time (pulse time) generated by
 * the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */